sudo ls -aRl ~/mnt/zepeto/40* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_40.txt
sudo ls -aRl ~/mnt/zepeto/41* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_41.txt
sudo ls -aRl ~/mnt/zepeto/42* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_42.txt
sudo ls -aRl ~/mnt/zepeto/43* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_43.txt
sudo ls -aRl ~/mnt/zepeto/44* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_44.txt
sudo ls -aRl ~/mnt/zepeto/45* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_45.txt
sudo ls -aRl ~/mnt/zepeto/46* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_46.txt
sudo ls -aRl ~/mnt/zepeto/47* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_47.txt
sudo ls -aRl ~/mnt/zepeto/48* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_48.txt
sudo ls -aRl ~/mnt/zepeto/49* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_49.txt
sudo ls -aRl ~/mnt/zepeto/4a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_4a.txt
sudo ls -aRl ~/mnt/zepeto/4b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_4b.txt
sudo ls -aRl ~/mnt/zepeto/4c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_4c.txt
sudo ls -aRl ~/mnt/zepeto/4d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_4d.txt
sudo ls -aRl ~/mnt/zepeto/4e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_4e.txt
sudo ls -aRl ~/mnt/zepeto/4f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_4f.txt
sudo ls -aRl ~/mnt/zepeto/50* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_50.txt
sudo ls -aRl ~/mnt/zepeto/51* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_51.txt
sudo ls -aRl ~/mnt/zepeto/52* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_52.txt
sudo ls -aRl ~/mnt/zepeto/53* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_53.txt
sudo ls -aRl ~/mnt/zepeto/54* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_54.txt
sudo ls -aRl ~/mnt/zepeto/55* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_55.txt
sudo ls -aRl ~/mnt/zepeto/56* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_56.txt
sudo ls -aRl ~/mnt/zepeto/57* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_57.txt
sudo ls -aRl ~/mnt/zepeto/58* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_58.txt
sudo ls -aRl ~/mnt/zepeto/59* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_59.txt
sudo ls -aRl ~/mnt/zepeto/5a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_5a.txt
sudo ls -aRl ~/mnt/zepeto/5b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_5b.txt
sudo ls -aRl ~/mnt/zepeto/5c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_5c.txt
sudo ls -aRl ~/mnt/zepeto/5d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_5d.txt
sudo ls -aRl ~/mnt/zepeto/5e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_5e.txt
sudo ls -aRl ~/mnt/zepeto/5f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_5f.txt
