sudo ls -aRl ~/mnt/zepeto/60* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_60.txt
sudo ls -aRl ~/mnt/zepeto/61* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_61.txt
sudo ls -aRl ~/mnt/zepeto/62* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_62.txt
sudo ls -aRl ~/mnt/zepeto/63* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_63.txt
sudo ls -aRl ~/mnt/zepeto/64* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_64.txt
sudo ls -aRl ~/mnt/zepeto/65* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_65.txt
sudo ls -aRl ~/mnt/zepeto/66* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_66.txt
sudo ls -aRl ~/mnt/zepeto/67* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_67.txt
sudo ls -aRl ~/mnt/zepeto/68* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_68.txt
sudo ls -aRl ~/mnt/zepeto/69* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_69.txt
sudo ls -aRl ~/mnt/zepeto/6a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_6a.txt
sudo ls -aRl ~/mnt/zepeto/6b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_6b.txt
sudo ls -aRl ~/mnt/zepeto/6c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_6c.txt
sudo ls -aRl ~/mnt/zepeto/6d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_6d.txt
sudo ls -aRl ~/mnt/zepeto/6e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_6e.txt
sudo ls -aRl ~/mnt/zepeto/6f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_6f.txt
sudo ls -aRl ~/mnt/zepeto/70* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_70.txt
sudo ls -aRl ~/mnt/zepeto/71* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_71.txt
sudo ls -aRl ~/mnt/zepeto/72* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_72.txt
sudo ls -aRl ~/mnt/zepeto/73* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_73.txt
sudo ls -aRl ~/mnt/zepeto/74* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_74.txt
sudo ls -aRl ~/mnt/zepeto/75* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_75.txt
sudo ls -aRl ~/mnt/zepeto/76* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_76.txt
sudo ls -aRl ~/mnt/zepeto/77* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_77.txt
sudo ls -aRl ~/mnt/zepeto/78* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_78.txt
sudo ls -aRl ~/mnt/zepeto/79* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_79.txt
sudo ls -aRl ~/mnt/zepeto/7a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_7a.txt
sudo ls -aRl ~/mnt/zepeto/7b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_7b.txt
sudo ls -aRl ~/mnt/zepeto/7c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_7c.txt
sudo ls -aRl ~/mnt/zepeto/7d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_7d.txt
sudo ls -aRl ~/mnt/zepeto/7e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_7e.txt
sudo ls -aRl ~/mnt/zepeto/7f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_7f.txt
