sudo ls -aRl ~/mnt/zepeto/c0* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c0.txt
sudo ls -aRl ~/mnt/zepeto/c1* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c1.txt
sudo ls -aRl ~/mnt/zepeto/c2* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c2.txt
sudo ls -aRl ~/mnt/zepeto/c3* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c3.txt
sudo ls -aRl ~/mnt/zepeto/c4* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c4.txt
sudo ls -aRl ~/mnt/zepeto/c5* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c5.txt
sudo ls -aRl ~/mnt/zepeto/c6* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c6.txt
sudo ls -aRl ~/mnt/zepeto/c7* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c7.txt
sudo ls -aRl ~/mnt/zepeto/c8* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c8.txt
sudo ls -aRl ~/mnt/zepeto/c9* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_c9.txt
sudo ls -aRl ~/mnt/zepeto/ca* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ca.txt
sudo ls -aRl ~/mnt/zepeto/cb* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_cb.txt
sudo ls -aRl ~/mnt/zepeto/cc* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_cc.txt
sudo ls -aRl ~/mnt/zepeto/cd* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_cd.txt
sudo ls -aRl ~/mnt/zepeto/ce* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ce.txt
sudo ls -aRl ~/mnt/zepeto/cf* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_cf.txt
sudo ls -aRl ~/mnt/zepeto/d0* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d0.txt
sudo ls -aRl ~/mnt/zepeto/d1* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d1.txt
sudo ls -aRl ~/mnt/zepeto/d2* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d2.txt
sudo ls -aRl ~/mnt/zepeto/d3* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d3.txt
sudo ls -aRl ~/mnt/zepeto/d4* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d4.txt
sudo ls -aRl ~/mnt/zepeto/d5* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d5.txt
sudo ls -aRl ~/mnt/zepeto/d6* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d6.txt
sudo ls -aRl ~/mnt/zepeto/d7* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d7.txt
sudo ls -aRl ~/mnt/zepeto/d8* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d8.txt
sudo ls -aRl ~/mnt/zepeto/d9* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_d9.txt
sudo ls -aRl ~/mnt/zepeto/da* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_da.txt
sudo ls -aRl ~/mnt/zepeto/db* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_db.txt
sudo ls -aRl ~/mnt/zepeto/dc* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_dc.txt
sudo ls -aRl ~/mnt/zepeto/dd* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_dd.txt
sudo ls -aRl ~/mnt/zepeto/de* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_de.txt
sudo ls -aRl ~/mnt/zepeto/df* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_df.txt
