sudo ls -aRl ~/mnt/zepeto/80* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_80.txt
sudo ls -aRl ~/mnt/zepeto/81* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_81.txt
sudo ls -aRl ~/mnt/zepeto/82* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_82.txt
sudo ls -aRl ~/mnt/zepeto/83* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_83.txt
sudo ls -aRl ~/mnt/zepeto/84* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_84.txt
sudo ls -aRl ~/mnt/zepeto/85* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_85.txt
sudo ls -aRl ~/mnt/zepeto/86* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_86.txt
sudo ls -aRl ~/mnt/zepeto/87* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_87.txt
sudo ls -aRl ~/mnt/zepeto/88* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_88.txt
sudo ls -aRl ~/mnt/zepeto/89* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_89.txt
sudo ls -aRl ~/mnt/zepeto/8a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_8a.txt
sudo ls -aRl ~/mnt/zepeto/8b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_8b.txt
sudo ls -aRl ~/mnt/zepeto/8c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_8c.txt
sudo ls -aRl ~/mnt/zepeto/8d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_8d.txt
sudo ls -aRl ~/mnt/zepeto/8e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_8e.txt
sudo ls -aRl ~/mnt/zepeto/8f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_8f.txt
sudo ls -aRl ~/mnt/zepeto/90* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_90.txt
sudo ls -aRl ~/mnt/zepeto/91* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_91.txt
sudo ls -aRl ~/mnt/zepeto/92* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_92.txt
sudo ls -aRl ~/mnt/zepeto/93* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_93.txt
sudo ls -aRl ~/mnt/zepeto/94* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_94.txt
sudo ls -aRl ~/mnt/zepeto/95* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_95.txt
sudo ls -aRl ~/mnt/zepeto/96* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_96.txt
sudo ls -aRl ~/mnt/zepeto/97* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_97.txt
sudo ls -aRl ~/mnt/zepeto/98* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_98.txt
sudo ls -aRl ~/mnt/zepeto/99* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_99.txt
sudo ls -aRl ~/mnt/zepeto/9a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_9a.txt
sudo ls -aRl ~/mnt/zepeto/9b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_9b.txt
sudo ls -aRl ~/mnt/zepeto/9c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_9c.txt
sudo ls -aRl ~/mnt/zepeto/9d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_9d.txt
sudo ls -aRl ~/mnt/zepeto/9e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_9e.txt
sudo ls -aRl ~/mnt/zepeto/9f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_9f.txt
