sudo ls -aRl ~/mnt/zepeto/20* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_20.txt
sudo ls -aRl ~/mnt/zepeto/21* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_21.txt
sudo ls -aRl ~/mnt/zepeto/22* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_22.txt
sudo ls -aRl ~/mnt/zepeto/23* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_23.txt
sudo ls -aRl ~/mnt/zepeto/24* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_24.txt
sudo ls -aRl ~/mnt/zepeto/25* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_25.txt
sudo ls -aRl ~/mnt/zepeto/26* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_26.txt
sudo ls -aRl ~/mnt/zepeto/27* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_27.txt
sudo ls -aRl ~/mnt/zepeto/28* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_28.txt
sudo ls -aRl ~/mnt/zepeto/29* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_29.txt
sudo ls -aRl ~/mnt/zepeto/2a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_2a.txt
sudo ls -aRl ~/mnt/zepeto/2b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_2b.txt
sudo ls -aRl ~/mnt/zepeto/2c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_2c.txt
sudo ls -aRl ~/mnt/zepeto/2d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_2d.txt
sudo ls -aRl ~/mnt/zepeto/2e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_2e.txt
sudo ls -aRl ~/mnt/zepeto/2f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_2f.txt
sudo ls -aRl ~/mnt/zepeto/30* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_30.txt
sudo ls -aRl ~/mnt/zepeto/31* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_31.txt
sudo ls -aRl ~/mnt/zepeto/32* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_32.txt
sudo ls -aRl ~/mnt/zepeto/33* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_33.txt
sudo ls -aRl ~/mnt/zepeto/34* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_34.txt
sudo ls -aRl ~/mnt/zepeto/35* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_35.txt
sudo ls -aRl ~/mnt/zepeto/36* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_36.txt
sudo ls -aRl ~/mnt/zepeto/37* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_37.txt
sudo ls -aRl ~/mnt/zepeto/38* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_38.txt
sudo ls -aRl ~/mnt/zepeto/39* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_39.txt
sudo ls -aRl ~/mnt/zepeto/3a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_3a.txt
sudo ls -aRl ~/mnt/zepeto/3b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_3b.txt
sudo ls -aRl ~/mnt/zepeto/3c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_3c.txt
sudo ls -aRl ~/mnt/zepeto/3d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_3d.txt
sudo ls -aRl ~/mnt/zepeto/3e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_3e.txt
sudo ls -aRl ~/mnt/zepeto/3f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_3f.txt
