sudo ls -aRl ~/mnt/zepeto/a0* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a0.txt
sudo ls -aRl ~/mnt/zepeto/a1* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a1.txt
sudo ls -aRl ~/mnt/zepeto/a2* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a2.txt
sudo ls -aRl ~/mnt/zepeto/a3* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a3.txt
sudo ls -aRl ~/mnt/zepeto/a4* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a4.txt
sudo ls -aRl ~/mnt/zepeto/a5* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a5.txt
sudo ls -aRl ~/mnt/zepeto/a6* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a6.txt
sudo ls -aRl ~/mnt/zepeto/a7* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a7.txt
sudo ls -aRl ~/mnt/zepeto/a8* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a8.txt
sudo ls -aRl ~/mnt/zepeto/a9* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_a9.txt
sudo ls -aRl ~/mnt/zepeto/aa* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_aa.txt
sudo ls -aRl ~/mnt/zepeto/ab* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ab.txt
sudo ls -aRl ~/mnt/zepeto/ac* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ac.txt
sudo ls -aRl ~/mnt/zepeto/ad* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ad.txt
sudo ls -aRl ~/mnt/zepeto/ae* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ae.txt
sudo ls -aRl ~/mnt/zepeto/af* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_af.txt
sudo ls -aRl ~/mnt/zepeto/b0* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b0.txt
sudo ls -aRl ~/mnt/zepeto/b1* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b1.txt
sudo ls -aRl ~/mnt/zepeto/b2* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b2.txt
sudo ls -aRl ~/mnt/zepeto/b3* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b3.txt
sudo ls -aRl ~/mnt/zepeto/b4* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b4.txt
sudo ls -aRl ~/mnt/zepeto/b5* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b5.txt
sudo ls -aRl ~/mnt/zepeto/b6* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b6.txt
sudo ls -aRl ~/mnt/zepeto/b7* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b7.txt
sudo ls -aRl ~/mnt/zepeto/b8* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b8.txt
sudo ls -aRl ~/mnt/zepeto/b9* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_b9.txt
sudo ls -aRl ~/mnt/zepeto/ba* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ba.txt
sudo ls -aRl ~/mnt/zepeto/bb* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_bb.txt
sudo ls -aRl ~/mnt/zepeto/bc* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_bc.txt
sudo ls -aRl ~/mnt/zepeto/bd* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_bd.txt
sudo ls -aRl ~/mnt/zepeto/be* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_be.txt
sudo ls -aRl ~/mnt/zepeto/bf* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_bf.txt
