sudo ls -aRl ~/mnt/zepeto/00* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_00.txt
sudo ls -aRl ~/mnt/zepeto/01* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_01.txt
sudo ls -aRl ~/mnt/zepeto/02* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_02.txt
sudo ls -aRl ~/mnt/zepeto/03* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_03.txt
sudo ls -aRl ~/mnt/zepeto/04* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_04.txt
sudo ls -aRl ~/mnt/zepeto/05* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_05.txt
sudo ls -aRl ~/mnt/zepeto/06* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_06.txt
sudo ls -aRl ~/mnt/zepeto/07* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_07.txt
sudo ls -aRl ~/mnt/zepeto/08* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_08.txt
sudo ls -aRl ~/mnt/zepeto/09* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_09.txt
sudo ls -aRl ~/mnt/zepeto/0a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_0a.txt
sudo ls -aRl ~/mnt/zepeto/0b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_0b.txt
sudo ls -aRl ~/mnt/zepeto/0c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_0c.txt
sudo ls -aRl ~/mnt/zepeto/0d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_0d.txt
sudo ls -aRl ~/mnt/zepeto/0e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_0e.txt
sudo ls -aRl ~/mnt/zepeto/0f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_0f.txt
sudo ls -aRl ~/mnt/zepeto/10* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_10.txt
sudo ls -aRl ~/mnt/zepeto/11* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_11.txt
sudo ls -aRl ~/mnt/zepeto/12* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_12.txt
sudo ls -aRl ~/mnt/zepeto/13* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_13.txt
sudo ls -aRl ~/mnt/zepeto/14* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_14.txt
sudo ls -aRl ~/mnt/zepeto/15* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_15.txt
sudo ls -aRl ~/mnt/zepeto/16* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_16.txt
sudo ls -aRl ~/mnt/zepeto/17* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_17.txt
sudo ls -aRl ~/mnt/zepeto/18* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_18.txt
sudo ls -aRl ~/mnt/zepeto/19* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_19.txt
sudo ls -aRl ~/mnt/zepeto/1a* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_1a.txt
sudo ls -aRl ~/mnt/zepeto/1b* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_1b.txt
sudo ls -aRl ~/mnt/zepeto/1c* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_1c.txt
sudo ls -aRl ~/mnt/zepeto/1d* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_1d.txt
sudo ls -aRl ~/mnt/zepeto/1e* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_1e.txt
sudo ls -aRl ~/mnt/zepeto/1f* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_1f.txt
