sudo ls -aRl ~/mnt/zepeto/e0* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e0.txt
sudo ls -aRl ~/mnt/zepeto/e1* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e1.txt
sudo ls -aRl ~/mnt/zepeto/e2* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e2.txt
sudo ls -aRl ~/mnt/zepeto/e3* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e3.txt
sudo ls -aRl ~/mnt/zepeto/e4* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e4.txt
sudo ls -aRl ~/mnt/zepeto/e5* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e5.txt
sudo ls -aRl ~/mnt/zepeto/e6* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e6.txt
sudo ls -aRl ~/mnt/zepeto/e7* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e7.txt
sudo ls -aRl ~/mnt/zepeto/e8* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e8.txt
sudo ls -aRl ~/mnt/zepeto/e9* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_e9.txt
sudo ls -aRl ~/mnt/zepeto/ea* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ea.txt
sudo ls -aRl ~/mnt/zepeto/eb* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_eb.txt
sudo ls -aRl ~/mnt/zepeto/ec* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ec.txt
sudo ls -aRl ~/mnt/zepeto/ed* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ed.txt
sudo ls -aRl ~/mnt/zepeto/ee* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ee.txt
sudo ls -aRl ~/mnt/zepeto/ef* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ef.txt
sudo ls -aRl ~/mnt/zepeto/f0* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f0.txt
sudo ls -aRl ~/mnt/zepeto/f1* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f1.txt
sudo ls -aRl ~/mnt/zepeto/f2* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f2.txt
sudo ls -aRl ~/mnt/zepeto/f3* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f3.txt
sudo ls -aRl ~/mnt/zepeto/f4* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f4.txt
sudo ls -aRl ~/mnt/zepeto/f5* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f5.txt
sudo ls -aRl ~/mnt/zepeto/f6* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f6.txt
sudo ls -aRl ~/mnt/zepeto/f7* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f7.txt
sudo ls -aRl ~/mnt/zepeto/f8* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f8.txt
sudo ls -aRl ~/mnt/zepeto/f9* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_f9.txt
sudo ls -aRl ~/mnt/zepeto/fa* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_fa.txt
sudo ls -aRl ~/mnt/zepeto/fb* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_fb.txt
sudo ls -aRl ~/mnt/zepeto/fc* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_fc.txt
sudo ls -aRl ~/mnt/zepeto/fd* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_fd.txt
sudo ls -aRl ~/mnt/zepeto/fe* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_fe.txt
sudo ls -aRl ~/mnt/zepeto/ff* | grep -v irteam | grep -v rwxrwxrwx | grep -v -e "^/home/irteam" | grep -v -e '^$' | grep -v "total " > test_check_ff.txt
